// <auto-generated />
using System;
using Gochs.ProtectiveStructures.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gochs.ProtectiveStructures.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261007055708_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("Gochs.ProtectiveStructures.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonnelNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProtectiveStructureId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonnelNumber")
                        .IsUnique();

                    b.HasIndex("ProtectiveStructureId");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("Gochs.ProtectiveStructures.Entities.Inspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Findings")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("InspectionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InspectorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("NextInspectionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProtectiveStructureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequiredActions")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultCondition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProtectiveStructureId");

                    b.ToTable("Inspections", (string)null);
                });

            modelBuilder.Entity("Gochs.ProtectiveStructures.Entities.ProtectiveStructure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponsiblePerson")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.ToTable("ProtectiveStructures", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProtectiveStructures_Capacity_Positive", "\"Capacity\" > 0");
                        });
                });

            modelBuilder.Entity("Gochs.ProtectiveStructures.Entities.Employee", b =>
                {
                    b.HasOne("Gochs.ProtectiveStructures.Entities.ProtectiveStructure", "ProtectiveStructure")
                        .WithMany("Employees")
                        .HasForeignKey("ProtectiveStructureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProtectiveStructure");
                });

            modelBuilder.Entity("Gochs.ProtectiveStructures.Entities.Inspection", b =>
                {
                    b.HasOne("Gochs.ProtectiveStructures.Entities.ProtectiveStructure", "ProtectiveStructure")
                        .WithMany("Inspections")
                        .HasForeignKey("ProtectiveStructureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProtectiveStructure");
                });

            modelBuilder.Entity("Gochs.ProtectiveStructures.Entities.ProtectiveStructure", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Inspections");
                });
#pragma warning restore 612, 618
        }
    }
}
